name: Build monitor-input Windows

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build monitor-input
      run: cargo install --path . -F winapp --locked --force
    - name: Copy binaries
      run: |
        mkdir release
        copy $HOME\.cargo\bin\monitor-input.exe release\
        copy $HOME\.cargo\bin\monitor-inputw.exe release\
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: monitor-input-exes
        path: release/
